#!/bin/bash
# Downloads and Installs Latest Release of 'starship'
# https://wiki.hyprland.org/Getting-Started/Quick-start/#wrapping-the-launcher-recommended

# shellcheck disable=SC2164
cd ~/

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export WLR_RENDERER_ALLOW_SOFTWARE=1
export WLR_NO_HARDWARE_CURSORS="1"

exec Hyprland