# alacritty.toml
# https://alacritty.org/config-alacritty-bindings.html
#  Custom Themes Repo
# https://github.com/rajasegar/alacritty-themes
#  Official Themes Repo
# https://github.com/alacritty/alacritty-theme
#  Docs
# https://alacritty.org/config-alacritty.html

import = ["/home/mike/.config/alacritty/fonts/jetbrains_fonts.toml", "/home/mike/.config/alacritty/themes/Tokyonight_Night.toml"]

shell = { program = "/bin/bash" }

# args = ["-l", "-c", "tmux a || tmux"

live_config_reload = true


[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Z"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "n"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F12"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "q"
mods = "Ctrl+Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "f"
mods = "Ctrl+Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "b"
mods = "Ctrl+Shift"

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3


[window]
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

#startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"



[window.padding]
x = 6
y = 6
