# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# Downloaded 2025-04-25
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
# ONLY INCLUDE THOSE ITEMS WHICH YOU CHANGE!

"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 2, 4, 3 ] # Modified: Mike
show_hidden    = true # Modified: Mike
