#!/bin/bash
# Configure .bashrc
# Install aliases and starship


declare baseSetups5Dir="$HOME"/bashOps/setups

source "$baseSetups5Dir"/utils/utilsLib.sh
source "$baseSetups5Dir"/utils/utilsAppInstall.sh

msgNotify "Installing 'eza'" &&
installEza &&
msgNotify "Installing 'micro'" &&
installMicro &&
msgNotify "Installing 'broot'" &&
installBroot &&
msgNotify "Installing 'btop'" &&
installBtop &&
msgNotify "Installing 'fd'(find)" &&
installFd &&
msgNotify "Installing 'fzf'(Fuzzy Finder)" &&
installFuzzyFinder &&
msgNotify "Installing 'fkill'(Process Killer)" &&
installFkill &&
msgNotify "Installing 'mc'(Midnight Commander)" &&
installMidnightCommander &&
msgNotify "Installing 'bash-completion'" &&
installBashCompletion &&
msgNotify "Installing 'bat'" &&
installBat &&
msgNotify "Installing 'tldr'" &&
installTldr &&
msgNotify "Installing 'zoxide'" &&
installZoxide &&
msgNotify "Installing 'trash-cli'" &&
installTrash &&
msgNotify "Installing 'ghq'" &&
installScriptGHQ &&
successMsg "All Phase-3 Utilities Installed." "003-utilitiesInstall" || errXMsg "003-utilitiesInstall Execution Failed" "Error-Exit!"