#!/bin/bash
# Configure .bashrc
# Install aliases and starship


declare baseSetups5Dir="$HOME"/bashOps/setups

source "$baseSetups5Dir"/utils/utilsLib.sh
source "$baseSetups5Dir"/utils/utilsAppInstall.sh
source "$baseSetups5Dir"/utils/utilsAppConfig.sh

msgNotify "Installing 'micro'" &&
installMicro &&
msgNotify "Installing 'btop'" &&
installBtop &&
msgNotify "Installing 'btm' (Bottom)" &&
installBottom &&
msgNotify "Installing 'fd'(find)" &&
installFd &&
msgNotify "Installing 'plocate'" &&
installPlocate &&
msgNotify "Installing 'fzf'(Fuzzy Finder)" &&
installFuzzyFinder &&
msgNotify "Installing 'fkill'(Process Killer)" &&
installFkill &&
msgNotify "Installing 'procs'(Process Viewer)" &&
installProcs &&
msgNotify "Installing 'mc'(Midnight Commander)" &&
installMidnightCommander &&
msgNotify "Installing 'tldr'" &&
installTldr &&
msgNotify "Installing 'lshw'" &&
installLshw &&
msgNotify "Installing 'ghq'" &&
installScriptGHQ &&
msgNotify "Installing 'ncurses' dependency for 'multitail' " &&
installNcurses &&
msgNotify "Installing 'multitail'" &&
installMultiTail &&
msgNotify "Installing fastfetch" &&
installFastFetch &&
msgNotify "Installing ripgrep" &&
installRipGrep &&
msgNotify "Installing Peco" &&
installScriptPeco &&
msgNotify "Installing Compression Utilities" &&
installCompressionUtilities &&
msgNotify "Installing VmWare Tools" &&
installVmwareTools &&
successMsg "All Phase-3 Utilities Installed." "003-utilitiesInstall" || errXMsg "003-utilitiesInstall Execution Failed" "Error-Exit!"